
# This CI will launch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 
# container:
#       image: continuumio/miniconda3:23.3.1-0

name: CI with install

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install non pypi dependencies
        shell: bash
        run: |
          wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash Miniforge3.sh -b -p "${HOME}/conda"
          source "${HOME}/conda/etc/profile.d/conda.sh"
          source "${HOME}/conda/etc/profile.d/mamba.sh"
          sudo apt-get --allow-releaseinfo-change update
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y libgl1-mesa-glx libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev libosmesa6 libosmesa6-dev libgles2-mesa-dev libarchive-dev libpangocairo-1.0-0
          mamba activate
          mamba install -y -c cadquery -c conda-forge moab gmsh python-gmsh cadquery=master
          python -m pip install --upgrade pip 
          python -m pip install .
          python -c "import cad_to_dagmc"
          sudo apt install g++ cmake libhdf5-dev libpng-dev
          mkdir MOAB
          cd MOAB
          git clone  --single-branch --branch 5.4.1 --depth 1 https://bitbucket.org/fathomteam/moab.git
          mkdir build
          cd build
          cmake ../moab -DENABLE_HDF5=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/home/runner/work/cad_to_dagmc/cad_to_dagmc/MOAB -DENABLE_FORTRAN=OFF
          make
          sudo make install
          mkdir DAGMC
          cd DAGMC
          git clone --single-branch --branch v3.2.2 --depth 1 https://github.com/svalinn/DAGMC.git
          mkdir build
          cd build
          cmake ../DAGMC -DBUILD_TALLY=ON -DMOAB_DIR=/home/runner/work/cad_to_dagmc/cad_to_dagmc/MOAB -DBUILD_STATIC_EXE=OFF -DBUILD_STATIC_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/home/runner/work/cad_to_dagmc/cad_to_dagmc/DAGMC/
          sudo make install
          git clone --depth 1  --recurse-submodules https://github.com/openmc-dev/openmc.git openmc-repo
          cd openmc-repo
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          cd ..
          python -m pip install .
          cd ..
          python -m pip install .[tests]
          pytest tests -v
          cd examples
          python create_stp_files_for_examples.py
          python cadquery_assembly.py
          python cadquery_compound.py
          python cadquery_object_and_stp_file.py
          python cadquery_text.py
          python curved_cadquery_object.py
          python multiple_cadquery_objects.py
          python multiple_stp_files.py
          python single_stp_file_multiple_volumes.py
          python single_cadquery_object.py
          python single_stp_file.py
