
name: CI with install

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install non pypi dependencies
        shell: bash
        run: |
          wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash Miniforge3.sh -b -p "${HOME}/conda"
          source "${HOME}/conda/etc/profile.d/conda.sh"
          source "${HOME}/conda/etc/profile.d/mamba.sh"
          sudo apt-get --allow-releaseinfo-change update
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y libgl1-mesa-glx libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev libosmesa6 libosmesa6-dev libgles2-mesa-dev libarchive-dev libpangocairo-1.0-0
          mamba activate
          mamba create -y --name cad_to_dagmc python=3.10
          mamba activate cad_to_dagmc
          mamba install -y -c conda-forge moab>=5.3.0 gmsh python-gmsh ocp=7.7.2.0 cadquery=2.4.0
          python -m pip install --upgrade pip 
          python -m pip install .
          python -c "import cad_to_dagmc"
          python -m pip install .[tests]
          pytest -v tests/test_file_creation.py
          pytest -v tests/test_loading_from_file_vs_shape_object.py
          pytest -v tests/test_python_api.py
          pytest -v tests/test_version.py
          cd examples/surface_mesh
          python create_stp_files_for_examples.py
          python cadquery_assembly.py
          python cadquery_compound.py
          python cadquery_object_and_stp_file.py
          python cadquery_text.py
          python curved_cadquery_object_to_dagmc_surface_mesh.py
          python multiple_cadquery_objects.py
          python multiple_stp_files.py
          python single_stp_file_multiple_volumes.py
          python single_cadquery_object.py
          python single_stp_file.py
          cd ../..
          cd examples/unstrucutred_volume_mesh
          python curved_cadquery_object_to_dagmc_volume_mesh.py
          cd ../..
          pytest -v tests/test_model_creation_for_transport.py
          mamba activate base
          mamba create -y --name openmc python=3.10
          mamba activate openmc
          mamba install -y -c conda-forge moab>=5.3.0  "openmc=0.14.0=dagmc*nompi*"
          python -m pip install .[tests]
          pytest -v tests/test_package.py
          pytest -v tests/test_h5m_in_simulation.py
          pytest -v tests/test_h5m_in_transport.py
          cd examples/unstrucutred_volume_mesh
          python simulate_unstrucutred_volume_mesh_with_openmc.py
