
# This CI will launch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 
# container:
#       image: continuumio/miniconda3:23.3.1-0

name: CI with install

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - uses: conda-incubator/setup-miniconda@v2

      - name: install non pypi dependencies
        shell: bash
        run: |
          wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash Miniforge3.sh -b -p "${HOME}/conda"
          source "${HOME}/conda/etc/profile.d/conda.sh"
          source "${HOME}/conda/etc/profile.d/mamba.sh"
          sudo apt-get --allow-releaseinfo-change update
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y libgl1-mesa-glx libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev libosmesa6 libosmesa6-dev libgles2-mesa-dev libarchive-dev libpangocairo-1.0-0
          mamba activate
          mamba install -y -c cadquery -c conda-forge moab gmsh python-gmsh cadquery=master
          
      - name: install package
        run: |
          pip install .
          python -c "import cad_to_dagmc"
          mamba install -y -c conda-forge "openmc=0.13.3=dagmc*nompi*"

      - name: run examples
        run: |
          cd examples
          python create_stp_files_for_examples.py

      - name: run examples
        run: |
          cd examples
          python cadquery_assembly.py

      - name: run examples
        run: |
          cd examples
          python cadquery_compound.py

      - name: run examples
        run: |
          cd examples
          python cadquery_object_and_stp_file.py

      - name: run examples
        run: |
          cd examples
          python cadquery_text.py

      - name: run examples 1
        run: |
          cd examples
          python curved_cadquery_object.py

      - name: run examples 2
        run: |
          cd examples
          python multiple_cadquery_objects.py

      - name: run examples 3
        run: |
          cd examples
          python multiple_stp_files.py

      - name: run examples 4
        run: |
          cd examples
          python single_stp_file_multiple_volumes.py

      - name: run examples 5
        run: |
          cd examples

      - name: run examples 6
        run: |
          cd examples
          python single_cadquery_object.py

      - name: run examples 7
        run: |
          cd examples
          python single_stp_file.py

      - name: Run pytest
        run: |
          pip install .[tests]
          pytest tests -v
